### PR TITLE
Kniffel and clickable

### PR DESCRIPTION
**Pull request by nfsprodriver**

### CODE REVIEW

**Comment by mymike00** [comment]
if you accidentally tap on "switch-mode" while you're playing you lose all the progress made so far... so I added a confirmation popup
I'm not sure about the icons... what do you think?
immagine
other options are 
immagine immagine

**Comment by nfsprodriver** [comment]
Good point, it's great!

**Comment by mymike00** [comment]
I think the only thing missing now is something that tells the user the difference between the 2 modes

**Comment by nfsprodriver** [comment]
Okay, I'll rewrite the About text and commit...

**Comment by mymike00** [comment]
ok, sorry for the delay but here is it. I'm sorry to all you translators that have to re-translate the instructions (btw you can copy the instruction sub-strings from the `.po` before start translating and paste them as new translations)
I also thought about stealing the code from the [calendar app](https://gitlab.com/ubports/apps/calendar-app/blob/master/qml/DefaultHeader.qml) to show the sections inline with the title if there's enough space. I didn't had time for it. you can do it if you want, otherwise it'll be a feature for a future release

**Pull request merged**
